name: Update Subscription

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requests
        run: pip install requests

      - name: Run filter
        run: python filter.py

      - name: Commit & push
        run: |
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add filtered.txt
          git commit -m "Auto update" || exit 0
          git push
